[package]
name = "prometheus-cachet-glue"
version = "0.1.0"
authors = ["Jan Christian Grünhage <jcgruenhage@matrix.org>"]

[dependencies]
actix-web = "0.5"
serde = "1"
serde_derive = "1"
serde_json = "1"
fern = "0.5"
chrono = "0.4"
log = "0.4"
reqwest = "0.8"
hyper = "0.11"
futures = "0.1"
