[package]
name = "prometheus-cachet-glue"
version = "0.1.0"
authors = ["Jan Christian Grünhage <jcgruenhage@matrix.org>"]

[dependencies]
actix-web = "0.5.6"
serde = "1.0.44"
serde_derive = "1.0.44"
serde_json = "1.0.17"
fern = "0.5.5"
chrono = "0.4.2"
log = "0.4.1"
reqwest = "0.8.5"
hyper = "0.11.25"
